=== mayannaoliveira/readme-widget-hub/schema/badge.schema.json
{
  "$ref": "#/definitions/Badge",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Badge": {
      "additionalProperties": false,
      "description": "徽章数据结构",
      "properties": {
        "alert": {
          "additionalProperties": false,
          "description": "提示",
          "properties": {
            "message": {
              "description": "提示内容",
              "type": "string"
            },
            "type": {
              "default": "Tip",
              "description": "类型",
              "enum": [
                "Note",
                "Tip",
                "Important",
                "Warning",
                "Caution"
              ],
              "type": "string"
            }
          },
          "required": [
            "message"
          ],
          "type": "object"
        },
        "description": {
          "description": "描述",
          "type": "string"
        },
        "enabled": {
          "default": true,
          "description": "是否启用",
          "type": "boolean"
        },
        "index": {
          "default": 9999,
          "description": "显示顺序，数字越小越靠前",
          "type": "number"
        },
        "rule": {
          "additionalProperties": false,
          "description": "规则",
          "properties": {
            "URITemplate": {
              "description": "整体URL模板 URI Template",
              "type": "string"
            },
            "params": {
              "description": "路径参数",
              "items": {
                "$ref": "#/definitions/RuleItem"
              },
              "type": "array"
            },
            "query": {
              "description": "查询参数",
              "items": {
                "$ref": "#/definitions/RuleItem"
              },
              "type": "array"
            }
          },
          "required": [
            "URITemplate"
          ],
          "type": "object"
        },
        "tags": {
          "additionalProperties": false,
          "description": "标签",
          "properties": {
            "needLogin": {
              "description": "是否需要登录",
              "type": "boolean"
            },
            "officialDocsUrl": {
              "description": "官方文档地址",
              "type": "string"
            },
            "onlineToolUrl": {
              "description": "在线工具地址",
              "type": "string"
            },
            "repoUrl": {
              "description": "项目地址",
              "type": "string"
            }
          },
          "type": "object"
        },
        "title": {
          "description": "名称",
          "type": "string"
        },
        "useExamples": {
          "description": "示例",
          "items": {
            "$ref": "#/definitions/Example"
          },
          "type": "array"
        }
      },
      "required": [
        "title",
        "description",
        "rule",
        "useExamples"
      ],
      "type": "object"
    },
    "Example": {
      "additionalProperties": false,
      "description": "示例",
      "properties": {
        "explain": {
          "additionalProperties": false,
          "description": "说明",
          "properties": {
            "alt": {
              "description": "描述",
              "type": "string"
            },
            "annotate": {
              "description": "注释",
              "type": "string"
            },
            "src": {
              "description": "链接",
              "type": "string"
            }
          },
          "required": [
            "src"
          ],
          "type": "object"
        },
        "images": {
          "description": "图片",
          "items": {
            "$ref": "#/definitions/MarkdownImage"
          },
          "type": "array"
        }
      },
      "required": [
        "explain",
        "images"
      ],
      "type": "object"
    },
    "MarkdownImage": {
      "additionalProperties": false,
      "description": "Markdown 图片",
      "properties": {
        "alt": {
          "description": "描述",
          "type": "string"
        },
        "src": {
          "description": "链接",
          "type": "string"
        }
      },
      "required": [
        "src"
      ],
      "type": "object"
    },
    "RuleItem": {
      "additionalProperties": false,
      "description": "规则参数",
      "properties": {
        "default": {
          "description": "默认值",
          "type": "string"
        },
        "description": {
          "description": "说明",
          "type": "string"
        },
        "extDescription": {
          "description": "补充说明",
          "type": "string"
        },
        "name": {
          "description": "名称",
          "type": "string"
        },
        "type": {
          "description": "类型",
          "type": "string"
        }
      },
      "required": [
        "name",
        "type",
        "description"
      ],
      "type": "object"
    }
  }
}

=== mayannaoliveira/readme-widget-hub/badge/star-history.json
{
  "title": "GitHub 星标历史图（star-history/star-history）",
  "description": "Star History 一个可以显示 GitHub 项目的 star 历史图的徽章。",
  "tags": {
    "repoUrl": "https://github.com/star-history/star-history",
    "onlineToolUrl": "https://www.star-history.com",
    "officialDocsUrl": "https://www.star-history.com/blog/how-to-use-github-star-history"
  },
  "rule": {
    "query": [
      {
        "name": "repos",
        "type": "string[]",
        "description": "仓库名",
        "extDescription": "多个仓库名用逗号分隔，例如：`owner1/repo1,owner2/repo2`"
      },
      {
        "name": "type",
        "type": "string",
        "description": "显示类型",
        "extDescription": "可选值：`Date` `Timeline`"
      }
    ],
    "URITemplate": "https://api.star-history.com/svg{?repos,type}"
  },
  "useExamples": [
    {
      "explain": {
        "annotate": "star-history/star-history",
        "alt": "Star History Chart",
        "src": "https://api.star-history.com/svg?repos=star-history/star-history&type=Date"
      },
      "images": [
        {
          "alt": "Star History Chart",
          "src": "https://api.star-history.com/svg?repos=star-history/star-history&type=Date"
        }
      ]
    }
  ]
}

=== mayannaoliveira/readme-widget-hub/badges/repobeats.json
{
  "title": "GitHub 仓库分析图",
  "description": "为你的 GitHub 仓库提供惊艳的见解，让你的 README.md 增添一些吸引眼球的精彩内容。",
  "tags": {
    "repoUrl": "https://github.com/axiomhq",
    "onlineToolUrl": "https://repobeats.axiom.co/configs",
    "officialDocsUrl": "https://repobeats.axiom.co/",
    "needLogin": true
  },
  "rule": {
    "params": [
      {
        "name": "configId",
        "type": "string",
        "description": "配置 ID",
        "extDescription": "登录 [Repobeats](https://repobeats.axiom.co/) 后选择仓库后获取"
      }
    ],
    "URITemplate": "https://repobeats.axiom.co/api/embed/{configId}.svg"
  },
  "useExamples": [
    {
      "explain": {
        "annotate": "xiaohuohumax/badge-collection",
        "alt": "Repobeats analytics image",
        "src": "https://repobeats.axiom.co/api/embed/65971378c4d394852dd1d92144244cbe14f0639c.svg"
      },
      "images": [
        {
          "alt": "Repobeats analytics image",
          "src": "https://repobeats.axiom.co/api/embed/65971378c4d394852dd1d92144244cbe14f0639c.svg"
        }
      ]
    }
  ]
}

=== mayannaoliveira/readme-widget-hub/badge/readme-typing-svg.json
{
  "title": "Readme Typing SVG（denvercoder1/readme-typing-svg）",
  "description": "动态生成、可定制的 SVG，可模拟文本输入和删除效果，适用于个人主页、仓库或网站。",
  "tags": {
    "repoUrl": "https://github.com/denvercoder1/readme-typing-svg",
    "onlineToolUrl": "https://readme-typing-svg.demolab.com/demo/",
    "officialDocsUrl": "https://github.com/denvercoder1/readme-typing-svg?tab=readme-ov-file#-options"
  },
  "rule": {
    "query": [
      {
        "name": "lines",
        "type": "string",
        "default": "",
        "description": "显示的文本",
        "extDescription": "多行之间用 `;` 分隔，文本中空格使用 `+` 代替"
      },
      {
        "name": "height",
        "type": "number",
        "default": "50",
        "description": "输出 SVG 的高度"
      },
      {
        "name": "width",
        "type": "number",
        "default": "400",
        "description": "输出 SVG 的宽度"
      },
      {
        "name": "size",
        "type": "number",
        "default": "20",
        "description": "字体大小",
        "extDescription": "单位：像素"
      },
      {
        "name": "font",
        "type": "string",
        "default": "monospace",
        "description": "字体族",
        "extDescription": "任何 Google Fonts 中的字体"
      },
      {
        "name": "color",
        "type": "string",
        "default": "36BCF7",
        "description": "文本颜色",
        "extDescription": "十六进制代码不带 #"
      },
      {
        "name": "background",
        "type": "string",
        "default": "00000000",
        "description": "文本背景颜色",
        "extDescription": "十六进制代码不带 #"
      },
      {
        "name": "center",
        "type": "boolean",
        "default": "false",
        "description": "文本水平对齐方式",
        "extDescription": "可选值：true（水平居中）false（左对齐）"
      },
      {
        "name": "vCenter",
        "type": "boolean",
        "default": "false",
        "description": "文本垂直对齐方式",
        "extDescription": "可选值：true（垂直居中）false（居中上方）"
      },
      {
        "name": "multiline",
        "type": "boolean",
        "default": "false",
        "description": "文本换行显示方式",
        "extDescription": "可选值：true（换行显示）false（同一行重新显示）"
      },
      {
        "name": "duration",
        "type": "number",
        "default": "5000",
        "description": "单行打印持续时间"
      },
      {
        "name": "pause",
        "type": "number",
        "default": "0",
        "description": "行与行之间的暂停时间",
        "extDescription": "单位：毫秒"
      },
      {
        "name": "repeat",
        "type": "boolean",
        "default": "true",
        "description": "在最后一行之后循环回到第一行"
      },
      {
        "name": "separator",
        "type": "string",
        "default": ";",
        "description": "行参数中使用的分隔符"
      },
      {
        "name": "letterSpacing",
        "type": "string",
        "default": "normal",
        "description": "字母间距",
        "extDescription": "任何字母间距（letter-spacing）属性的 CSS 值"
      }
    ],
    "URITemplate": "https://readme-typing-svg.demolab.com{?lines,height,width,size,font,color,background,center,vCenter,multiline,duration,pause,repeat,separator,letterSpacing}"
  },
  "useExamples": [
    {
      "explain": {
        "alt": "Readme Typing SVG",
        "src": "https://readme-typing-svg.demolab.com?font=Fira+Code&pause=1000&width=435&lines=Hello+World;Badge+Collection"
      },
      "images": [
        {
          "alt": "Readme Typing SVG",
          "src": "https://readme-typing-svg.demolab.com?font=Fira+Code&pause=1000&width=435&lines=Hello+World;Badge+Collection"
        }
      ]
    }
  ]
}

=== mayannaoliveira/readme-widget-hub/badge/openssf-best-practices.json
{
  "title": "OpenSSF Best Practices 开源安全基金会最佳实践徽章（coreinfrastructure/best-practices-badge）",
  "description": "本项目确定了自由/开源软件（FLOSS）的最佳实践，并为这些最佳实践实施了一个徽章系统。",
  "tags": {
    "repoUrl": "https://github.com/coreinfrastructure/best-practices-badge",
    "onlineToolUrl": "https://www.bestpractices.dev",
    "needLogin": true
  },
  "rule": {
    "params": [
      {
        "name": "id",
        "type": "string",
        "description": "项目 ID"
      }
    ],
    "URITemplate": "https://www.bestpractices.dev/projects/{id}/badge"
  },
  "useExamples": [
    {
      "explain": {
        "annotate": "best-practices-badge",
        "alt": "OpenSSF Best Practices",
        "src": "https://www.bestpractices.dev/projects/7652/badge"
      },
      "images": [
        {
          "alt": "OpenSSF Best Practices",
          "src": "https://www.bestpractices.dev/projects/7652/badge"
        }
      ]
    }
  ]
}

=== mayannaoliveira/readme-widget-hub/badge/contributors-img.json
{
  "title": "GitHub 项目贡献者图（lacolaco/contributors-img）",
  "description": "生成一个贡献者图片，让你的 README.md 文件保持同步。",
  "tags": {
    "repoUrl": "https://github.com/lacolaco/contributors-img",
    "onlineToolUrl": "https://contrib.rocks/preview"
  },
  "rule": {
    "query": [
      {
        "name": "repo",
        "type": "string",
        "description": "仓库名",
        "extDescription": "格式：`owner/repo`"
      },
      {
        "name": "max",
        "type": "number",
        "default": "100",
        "description": "最大显示贡献者数"
      },
      {
        "name": "columns",
        "type": "number",
        "default": "12",
        "description": "显示列数"
      },
      {
        "name": "anon",
        "type": "number",
        "default": "0",
        "description": "是否显示匿名贡献者",
        "extDescription": "可选值：`0` `1`"
      }
    ],
    "URITemplate": "https://contrib.rocks/image{?repo,max,columns,anon}"
  },
  "useExamples": [
    {
      "explain": {
        "annotate": "lacolaco/contributors-img",
        "alt": "Contributors Image",
        "src": "https://contrib.rocks/image?repo=lacolaco/contributors-img"
      },
      "images": [
        {
          "alt": "Contributors Image",
          "src": "https://contrib.rocks/image?repo=lacolaco/contributors-img"
        }
      ]
    }
  ]
}

=== mayannaoliveira/readme-widget-hub/badge/template.json
{
  "enabled": false,
  "title": "",
  "description": "",
  "alert": {
    "type": "Tip",
    "message": ""
  },
  "tags": {
    "repoUrl": "",
    "onlineToolUrl": "",
    "officialDocsUrl": "",
    "needLogin": true
  },
  "rule": {
    "params": [
      {
        "name": "",
        "type": "",
        "default": "",
        "description": "",
        "extDescription": ""
      }
    ],
    "query": [],
    "URITemplate": ""
  },
  "useExamples": [
    {
      "explain": {
        "annotate": "",
        "alt": "",
        "src": ""
      },
      "images": [
        {
          "alt": "",
          "src": ""
        }
      ]
    }
  ]
}

=== mayannaoliveira/readme-widget-hub/badge/ossinsight.json
{
  "title": "Open Source Software Insight 开源软件洞察（pingcap/ossinsight）",
  "description": "在 30 秒内即可将实时小部件嵌入到仓库的 README.md 文件中！",
  "alert": {
    "type": "Tip",
    "message": "由于此项目支持的卡片种类非常多，且功能强大，这里只简单介绍－推送和提交记录卡片，其他卡片使用方式还请移步官方文档。"
  },
  "tags": {
    "repoUrl": "https://github.com/pingcap/ossinsight",
    "onlineToolUrl": "https://next.ossinsight.io/widgets/official/analyze-repo-pushes-and-commits-per-month?repo_id=449649595"
  },
  "rule": {
    "query": [
      {
        "name": "repo_id",
        "type": "string",
        "description": "Github 仓库 ID"
      },
      {
        "name": "color_scheme",
        "type": "string",
        "description": "卡片颜色主题",
        "extDescription": "可选值：`light` `dark`"
      }
    ],
    "URITemplate": "https://next.ossinsight.io/widgets/official/analyze-repo-pushes-and-commits-per-month{?repo_id,color_scheme}"
  },
  "useExamples": [
    {
      "explain": {
        "annotate": "pingcap/ossinsight",
        "alt": "Pushes and Commits of pingcap/ossinsight",
        "src": "https://next.ossinsight.io/widgets/official/analyze-repo-pushes-and-commits-per-month/thumbnail.png?repo_id=449649595&color_scheme=dark"
      },
      "images": [
        {
          "alt": "Pushes and Commits of pingcap/ossinsight",
          "src": "https://next.ossinsight.io/widgets/official/analyze-repo-pushes-and-commits-per-month/thumbnail.png?repo_id=449649595&color_scheme=dark"
        }
      ]
    },
    {
      "explain": {
        "annotate": "antfu",
        "alt": "Dashboard stats of @antfu",
        "src": "https://next.ossinsight.io/widgets/official/compose-user-dashboard-stats/thumbnail.png?user_id=11247099&image_size=auto&color_scheme=dark"
      },
      "images": [
        {
          "alt": "Dashboard stats of @antfu",
          "src": "https://next.ossinsight.io/widgets/official/compose-user-dashboard-stats/thumbnail.png?user_id=11247099&image_size=auto&color_scheme=dark"
        }
      ]
    }
  ]
}
